server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
      - id: baeldung_route
        uri: http://baeldung.com
        predicates:
        - Path=/baeldung/
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
