server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
      - id: baeldung_route
        uri: http://service-one:8020
        predicates:
        - Path=/service-one/
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
