server:
  port: 8083
spring:
  application:
    # Como nombre de servicio, no distingue entre mayúsculas y minúsculas
    name: kotlindemo
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
